import type { Metadata } from "next";
import { Roboto, Salsa } from "next/font/google";
import { AuthProvider } from "./context/Authcontext";
import "./globals.css";
import Header from "@/components/Header";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});
const salsa = Salsa({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className={salsa.className}>
          <AuthProvider>
            <Header />
            {children}
          </AuthProvider>
        </main>
      </body>
    </html>
  );
}
